### PR TITLE
Finish up Featured Listings, Organizations and Causes on main page

### PR DESCRIPTION
**Pull request by Kalsyc**
Tried my best to make it look okay-ish for now. Need to fix the min/max height and width

image

### CODE REVIEW

**Comment by don-tay** [comment]
For the categories, will it be visible against white background?

Also, what happens when there are more than 6 featured projects? Does it become a carousel?

**Comment by Kalsyc** [comment]
> For the categories, will it be visible against white background?
> 
> 
> 
> Also, what happens when there are more than 6 featured projects? Does it become a carousel?

1) Thats what I was afraid, I have asked Wayne and Xiaoyu about it.

2) I assumed that there are only 6 featured projects. (I can just limit it to the first 6) I actually think on mobile view, a carousel will work better.

**Comment by Kalsyc** [comment]
> > For the categories, will it be visible against white background?
> > Also, what happens when there are more than 6 featured projects? Does it become a carousel?
> 
> 1. Thats what I was afraid, I have asked Wayne and Xiaoyu about it.
> 2. I assumed that there are only 6 featured projects. (I can just limit it to the first 6) I actually think on mobile view, a carousel will work better.

1) I have placed the filter/background such that it'll be visible against a white background
2) I have forced the number of projects to only be 6 (In the future, we'll include the view more so that we can see all featured projects, (which will actually be part of the search page)

**Review by don-tay — APPROVED** [review]
LGTM

**Pull request merged**
